config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root "static_pages#home"
    get "static_pages/help"

    get "/signup", to: "users#new"
    post "/signup", to: "users#create"

    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
  end

  resources :users
  resources :account_activations, only: :edit
  resources :password_resets, except: %i(show index destroy)
  resources :microposts, only: %i(create destroy)
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user, :valid_user, :check_expiration, only: %i(edit update)

  def new; end

  def create
    @user = User.find_by email: params[:password_reset][:email].downcase
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = t "password_reset_controller_create.msg_info"
      redirect_to root_url
    else
      flash.now[:danger] = t "password_reset_controller_create.msg_danger"
      render :new
    end
  end

  def edit; end

  def update
    if params[:user][:password].empty?
      @user
        .errors.add(:password, t("password_reset_controller_update.msg_error"))
      render :edit
    elsif @user.update user_params
      log_in @user
      flash[:success] = t "password_reset_controller_update.msg_success"
      redirect_to @user
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit :password, :password_confirmation
  end

  def get_user
    @user = User.find_by email: params[:email]
  end

  def valid_user
    return if @user.activated && @user.authenticated?(:reset, params[:id])

    redirect_to root_url
  end

  def check_expiration
    return unless @user.password_reset_expired?

    flash[:danger] = t "password_reset_controller_check_expiration.msg"
    redirect_to new_password_reset_url
  end
end

app/views/password_resets/edit.html.erb
<% provide(:title, t("page_edit_password.title")) %>
<h1><%= t "page_edit_password.welcome" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
      <%= render "shared/error_messages", object: f.object %>
      <%= hidden_field_tag :email, @user.email %>
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
      <%= f.submit t("page_edit_password.submit"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<% provide :title, t("page_new_password.title") %>
<h1><%= t "page_new_password.welcome" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for :password_reset, url: password_resets_path do |f| %>
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>
      <%= f.submit t("page_new_password.submit"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>