config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root "static_pages#home"
    get "static_pages/help"

    get "/signup", to: "users#new"
    post "/signup", to: "users#create"

    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
  end

  resources :users
  resources :account_activations, only: :edit
  resources :password_resets, except: %i(show index destroy)
  resources :microposts, only: %i(create destroy)
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("global.header.sample_app"), "#", id: "logo" %>>
    <nav class="nav navbar-nav navbar-right">
      <ul class="nav navbar-nav navbar-right">
        <li class="nav-item"><%= link_to t("global.header.home"), root_path %></li>
        <li class="nav-item"><%= link_to t("global.header.help"), static_pages_help_path %></li>

        <% if logged_in? %>
          <li><%= link_to t("users"), users_path %></li>
          <li class="dropdown">
            <%= link_to "#", class: "btn btn-secondary dropdown-toggle", "data-toggle"=>"dropdown" do %>
              <%= t "dropdown.account" %>
              <b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to t("dropdown.profile"), current_user %></li>
              <li><%= link_to t("dropdown.setting"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to t("dropdown.logout"), logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("global.header.login"), login_path %></li>
        <% end %>
      </ul>
      <ul>
        <li><%= link_to t("global.header.option_en"), locale: :en %></li>
        <li><%= link_to t("global.header.option_vi"), locale: :vi %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application" %>

  </head>

  <body>

    <%= render "layouts/header" %>

    <div class="container">
      <div class="show_messages">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
      </div>
      <%= yield %>
    </div>
  </body>
  <script>
    I18n.defaultLocale = "<%= I18n.default_locale %>";
    I18n.locale = "<%= I18n.locale %>"
    I18n.translations = <%== I18n::JS.filtered_translations.to_json %>;
  </script>
</html>